services:
  nginx:
    container_name: nginx_pizzeria
    restart: on-failure
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 8888:8888
    depends_on:
      - web
  web:
    container_name: pizzeria_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - current.env
    command: sh -c "gunicorn pizzeria.wsgi:application --bind 0.0.0.0:5000"
    volumes:
     - static_volume:/app/static

volumes:
  static_volume:
