# Generated by Django 4.2 on 2023-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
